name: Trigger Jenkins Pipeline

on:
  push:
    branches:
      - main
      - test # <--- Add this line!

jobs:
  trigger_jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Build
        uses: jenkins-ci/trigger-pipeline@v1
        with:
          url: ${{ secrets.JENKINS_URL }}
          username: ${{ secrets.JENKINS_USERNAME }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job_name: 'your-jenkins-job-name'